// Copyright 2016 Patrick Brosi
// Authors: info@patrickbrosi.de

//
// Use of this source code is governed by a GPL v2
// license that can be found in the LICENSE file

package main

import (
	"fmt"
	"github.com/patrickbr/gtfsparser"
	"github.com/patrickbr/gtfsparser/gtfs"
	"github.com/patrickbr/gtfswriter"
	flag "github.com/spf13/pflag"
	"math"
	mail "net/mail"
	url "net/url"
	"os"
	"path"
	"patrickbrosi.de/vdv452parser"
	"patrickbrosi.de/vdv452parser/vdv452"
)

func main() {
	flag.Usage = func() {
		fmt.Fprintf(os.Stderr, "vdv4522gtfs - (C) 2016-2021 by P. Brosi <info@patrickbrosi.de>\n\nUsage:\n\n  %s [<options>] <input VDV452>\n\nAllowed options:\n\n", os.Args[0])
		flag.PrintDefaults()
	}

	help := flag.BoolP("help", "?", false, "this message")
	outputPath := flag.StringP("output", "o", "gtfs-out", "gtfs output directory or zip file (must end with .zip)")

	flag.Parse()

	if *help {
		flag.Usage()
		return
	}

	vdv452paths := flag.Args()

	if len(vdv452paths) == 0 {
		fmt.Fprintln(os.Stderr, "No VDV452 location specified, see --help")
		os.Exit(1)
	}

	// defer func() {
	// if r := recover(); r != nil {
	// fmt.Fprintln(os.Stderr, "Error:", r)
	// }
	// }()

	gtfsfeed := gtfsparser.NewFeed()

	feedinf := new(gtfs.FeedInfo)
	feedinf.Publisher_name = "gtfs.de"
	u, _ := url.ParseRequestURI("https://gtfs.de")
	feedinf.Publisher_url = u
	feedinf.Lang = "en"
	mail, _ := mail.ParseAddress("info@gtfs.de")
	feedinf.Contact_email = mail
	feedinf.Contact_url = u
	feedinf.Version = "generated by vdv2gtfs"
	gtfsfeed.FeedInfos = append(gtfsfeed.FeedInfos, feedinf)

	for _, ipath := range vdv452paths {
		fmt.Fprintf(os.Stdout, "Parsing VDV452 in '%s' ...", ipath)
		feed := vdv452parser.NewVDV452()
		feed.Parse(ipath)

		// collect calendar_dates.txt
		for _, dt := range feed.DayTypes {
			serviceid := fmt.Sprintf("%d", dt.DayTypeNo)
			service := new(gtfs.Service)
			service.Id = serviceid
			service.Daymap = [7]bool{false, false, false, false, false, false, false}
			service.Start_date = gtfs.Date{-1, -1, -1}
			service.End_date = gtfs.Date{-1, -1, -1}
			service.Exceptions = make(map[gtfs.Date]bool)
			gtfsfeed.Services[serviceid] = service

			for date, _ := range dt.OperatingDays {
				year := date / 10000
				month := date % 10000 / 100
				day := date % 10000 % 100
				service.Exceptions[gtfs.Date{int8(day), int8(month), int16(year)}] = true
			}
		}

		parentStops := make(map[uint][]uint64)

		// collect parent stops
		for sid, s := range feed.Stops {
			if _, ok := parentStops[s.Stop_No]; !ok {
				parentStops[s.Stop_No] = make([]uint64, 0)
			}
			parentStops[s.Stop_No] = append(parentStops[s.Stop_No], sid)
		}

		parentStopPointers := make(map[uint]*gtfs.Stop)

		for sid, stops := range parentStops {
			if len(stops) < 2 {
				continue
			}

			stop := new(gtfs.Stop)
			stop.Id = fmt.Sprintf("%d", sid)
			stop.Name = feed.Stops[stops[0]].Stop_Desc
			stop.Code = feed.Stops[stops[0]].Stop_Abbr
			stop.Location_type = 1

			lat := float32(0)
			lon := float32(0)

			for _, s := range stops {
				if feed.Stops[s].Latitude != 0 {
					lat += feed.Stops[s].Latitude
					lon += feed.Stops[s].Longitude
				}
			}

			lat = lat / float32(len(stops));
			lon = lon / float32(len(stops));

			stop.Lat =  lat
			stop.Lon =  lon

			gtfsfeed.Stops[stop.Id] = stop
			parentStopPointers[sid] = stop
		}

		// collect stops.txt
		for sid, s := range feed.Stops {
			stop := new(gtfs.Stop)
			stopid := fmt.Sprintf("%d", sid)
			stop.Id = stopid
			stop.Name = s.Stop_Desc
			stop.Lat = s.Latitude
			stop.Lon = s.Longitude
			stop.Code = s.Stop_Abbr
			if ps, ok := parentStopPointers[s.Stop_No]; ok {
				stop.Parent_station = ps
			}
			gtfsfeed.Stops[stopid] = stop
		}

		// collect agencies.txt
		for _, o := range feed.OperatingDepartments {
			agency := new(gtfs.Agency)
			agency.Id = fmt.Sprintf("%d", o.OpDepNo)
			agency.Name = o.OpDepDesc
			tz, _ := gtfs.NewTimezone("Europe/Berlin")
			agency.Timezone = tz
			lan, _ := gtfs.NewLanguageISO6391("en")
			agency.Lang = lan
			url, _ := url.ParseRequestURI("https://www.gtfs.de")
			agency.Url = url
			gtfsfeed.Agencies[agency.Id] = agency
		}

		// collect routes.txt
		for lid, l := range feed.Lines {
			route := new(gtfs.Route)
			route.Id = lid
			route.Short_name = l.LineAbbr
			route.Long_name = l.LineDesc
			route.Sort_order = -1
			gtfsfeed.Routes[route.Id] = route

			if _, ok := feed.OperatingDepartments[uint64(l.OpDepNo)]; ok {
				route.Agency = gtfsfeed.Agencies[fmt.Sprintf("%d", l.OpDepNo)]
			} else {
				panic(fmt.Errorf("Operating department not found: %d", l.OpDepNo))
			}
		}

		for _, j := range feed.Journeys {
			if j.JourneyType != 1 {
				continue
			}
			lineId := fmt.Sprintf("%06d", j.LineNo) + "." + j.RouteAbbr
			journeyDepTime := j.DepartureTime

			var l *vdv452.Line
			var ok bool

			if l, ok = feed.Lines[lineId]; !ok {
				fmt.Fprintln(os.Stderr, "WARN: Line not found:", lineId)
				continue
			}

			if len(l.Sequence) == 0 {
				continue
			}
			// dest := feed.Destinations[uint64(l.Sequence[0].DestNo)]
			// fmt.Fprintf(os.Stdout, "== Trip %d to '%s'== \n", j.JourneyNo)

			trip := new(gtfs.Trip)
			tripid := fmt.Sprintf("%d", j.JourneyNo)
			gtfsfeed.Trips[tripid] = trip
			trip.Id = tripid
			trip.Route = gtfsfeed.Routes[lineId]
			trip.Service = gtfsfeed.Services[fmt.Sprintf("%d", j.DayTypeNo)]
			trip.Direction_id = int8(l.Direction - 1)
			trip.Block_id = fmt.Sprintf("%d", j.BlockNo)
			if j.TrainNo > 0 {
				trip.Short_name = fmt.Sprintf("%d", j.TrainNo)
			} else {
				trip.Short_name = l.LineAbbr
			}

			if block, ok := feed.Blocks[uint64(j.DayTypeNo*1000+j.BlockNo)]; ok {
				veh := feed.VehicleTypes[uint64(block.VhTypeNo)]
				if veh.VhTypeSpecSeat > 0 {
					trip.Wheelchair_accessible = 1
				}
			} else {
				panic(fmt.Errorf("Block not found: %d | %d", j.DayTypeNo, j.BlockNo))
			}

			var prevStop *vdv452.Stop
			prevTime := 0
			prevHs := ""

			for _, s := range l.Sequence {
				// if s.Productive == 0 {
				// TODO
				// continue
				// }
				if stop, ok := feed.Stops[uint64(s.PointType)*7000000+uint64(s.PointNo)]; ok {
					stopid := fmt.Sprintf("%d", uint64(s.PointType)*7000000+uint64(s.PointNo))
					arrTime := 0
					depTime := 0
					if prevStop == nil {
						arrTime = journeyDepTime
						depTime = arrTime
					} else {

						tGroup := uint64(l.OpDepNo)*1000000000 + uint64(j.TimingGroupNo)
						ft := uint64(prevStop.Point_Type)*100000000000000 + uint64(prevStop.Point_No)*100000000 + uint64(stop.Point_Type)*1000000 + uint64(stop.Point_No)

						tGroupWait := uint64(j.TimingGroupNo)
						ftWait := uint64(stop.Point_Type)*1000000 + uint64(stop.Point_No)

						travelTime := feed.TravelTimes[tGroup][ft]
						waitTime := feed.WaitTimes[tGroupWait][ftWait]

						arrTime = prevTime + travelTime
						depTime = arrTime + waitTime
					}

					puType := int8(0)
					doType := int8(0)

					if s.RequestStop {
						puType = 2
					}

					if s.NoBoarding {
						puType = 1
					}

					if s.NoAlighting {
						doType = 1
					}

					headsign := ""

					if dest, ok := feed.Destinations[uint64(s.DestNo)]; ok {
						headsign = dest.DestFrontText
					}

					if len(headsign) > 0 {
						prevHs = headsign
					} else if len(prevHs) > 0 {
						headsign = prevHs
					}

					// times rounded to the nearest full minute
					rArrTime := 0
					rDepTime := 0

					if (arrTime % 3600 % 60) >= 30 {
						rArrTime = arrTime + (60 - (arrTime % 3600 % 60))
					} else {
						rArrTime = arrTime - (arrTime % 3600 % 60)
					}

					if (depTime % 3600 % 60) >= 30 {
						rDepTime = depTime + (60 - (depTime % 3600 % 60))
					} else {
						rDepTime = depTime - (depTime % 3600 % 60)
					}

					arrT := gtfs.Time{int8(rArrTime / 3600), int8(rArrTime % 3600 / 60), int8(rArrTime % 3600 % 60)}
					depT := gtfs.Time{int8(rDepTime / 3600), int8(rDepTime % 3600 / 60), int8(rDepTime % 3600 % 60)}

					trip.StopTimes = append(trip.StopTimes, gtfs.StopTime{arrT, depT, gtfsfeed.Stops[stopid], s.SequenceNo, headsign, puType, doType, float32(math.NaN()), true})

					prevStop = stop
					prevTime = depTime
				} else {
					panic(fmt.Errorf("Stop not found: %d | %d", s.PointType, s.PointNo))
				}
			}
		}

		fmt.Fprintf(os.Stdout, " done.\n")
		fmt.Fprintf(os.Stdout, "Outputting GTFS feed to '%s'...", *outputPath)

		if _, err := os.Stat(*outputPath); os.IsNotExist(err) {
			if path.Ext(*outputPath) == ".zip" {
				os.Create(*outputPath)
			} else {
				os.Mkdir(*outputPath, os.ModePerm)
			}
		}

		w := gtfswriter.Writer{ZipCompressionLevel: 9, Sorted: true}
		e := w.Write(gtfsfeed, *outputPath)

		if e != nil {
			fmt.Fprintf(os.Stderr, "\nError while writing GTFS feed in '%s':\n ", *outputPath)
			fmt.Fprintln(os.Stderr, e.Error())
			os.Exit(1)
		}

		fmt.Fprintf(os.Stdout, " done.\n")
	}
}
